service: captures-fabsoon-wedding

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.11
  region: ap-southeast-1
  stage: ${opt:stage, 'dev'}
  environment:
    BUCKET_NAME: ${self:custom.bucketName}
    IMAGES_TABLE: ${self:custom.imagesTableName}
    RSVP_TABLE: ${self:custom.rsvpTableName}
    STAGE: ${self:provider.stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:GetObject
      Resource: "arn:aws:s3:::${self:custom.bucketName}/*"
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:GetItem
        - dynamodb:Query
      Resource: 
        - "arn:aws:dynamodb:${self:provider.region}:*:table/${self:custom.imagesTableName}"
        - "arn:aws:dynamodb:${self:provider.region}:*:table/${self:custom.rsvpTableName}"
  logRetentionInDays: 120
  memorySize: 128
  timeout: 30

plugins:
    - serverless-python-requirements
    - serverless-prune-plugin
    - serverless-offline

custom:
  bucketName: ${self:provider.stage}-captures-fabsoon-wedding
  imagesTableName: ${self:provider.stage}-wedding-images
  rsvpTableName: ${self:provider.stage}-wedding-rsvp
  serverless-offline:
    httpPort: 3001
  
  prune:
    automatic: true
    includeLayers: true
    number: 3

functions:
  upload:
    handler: handler.upload_image
    events:
      - http:
          path: upload
          method: post
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
            allowCredentials: false
  rsvp:
    handler: handler.rsvp_handler
    events:
      - http:
          path: rsvp
          method: post
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
            allowCredentials: false

resources:
  Resources:
    ImagesBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.bucketName}
        CorsConfiguration:
          CorsRules:
            - AllowedOrigins:
                - "*"
              AllowedHeaders:
                - "*"
              AllowedMethods:
                - POST
              MaxAge: 3000

    RSVPTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.rsvpTableName}
        AttributeDefinitions:
          - AttributeName: email
            AttributeType: S
          - AttributeName: attendance
            AttributeType: S
          - AttributeName: created_at_gsi
            AttributeType: S
        KeySchema:
          - AttributeName: email
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: gsi1_attendance
            KeySchema:
              - AttributeName: attendance
                KeyType: HASH
            Projection:
              ProjectionType: ALL
          - IndexName: gsi2_created_at
            KeySchema:
              - AttributeName: created_at_gsi
                KeyType: HASH
            Projection:
              ProjectionType: ALL
        BillingMode: PAY_PER_REQUEST